

const jokers = [
    {
        id:1,
        name:"Joker",
        text:"",
        rarity:1,
        price:2
    },
    {
        id:2,
        name:"Greedy Joker",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:3,
        name:"Lusty Joker",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:4,
        name:"Wrathful Joker",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:5,
        name:"Gluttonous Joker",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:6,
        name:"Jolly Joker",
        text:"",
        rarity:1,
        price:3
    },
    {
        id:7,
        name:"Zany Joker",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:8,
        name:"Mad Joker",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:9,
        name:"Crazy Joker",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:10,
        name:"Droll Joker",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:11,
        name:"Sly Joker",
        text:"",
        rarity:1,
        price:3
    },
    {
        id:12,
        name:"Wily Joker",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:13,
        name:"Clever Joker",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:14,
        name:"Devious Joker",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:15,
        name:"Crafty Joker",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:16,
        name:"Half Joker",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:17,
        name:"Joker Stencil",
        text:"",
        rarity:2,
        price:8
    },
    {
        id:18,
        name:"Four Fingers",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:19,
        name:"Mime",
        text:"",
        rarity:2,
        price:5
    },
    {
        id:20,
        name:"Credit Card",
        text:"",
        rarity:1,
        price:1
    },
    {
        id:21,
        name:"Ceremonial Dagger",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:22,
        name:"Banner",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:23,
        name:"Mystic Summit",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:24,
        name:"Marble Joker",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:25,
        name:"Loyalty Card",
        text:"",
        rarity:2,
        price:5
    },
    {
        id:26,
        name:"8 Ball",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:27,
        name:"Misprint",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:28,
        name:"Dusk",
        text:"",
        rarity:2,
        price:5
    },
    {
        id:29,
        name:"Raised Fist",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:30,
        name:"Chaos the Clown",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:31,
        name:"Fibonacci",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:32,
        name:"Steel Joker",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:33,
        name:"Scary Face",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:34,
        name:"Abstract Joker",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:35,
        name:"Delayed Gratification",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:36,
        name:"Hack",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:37,
        name:"Pareidolia",
        text:"",
        rarity:2,
        price:5
    },
    {
        id:38,
        name:"Gros Michel",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:39,
        name:"Even Steven",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:40,
        name:"Odd Todd",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:41,
        name:"Scholar",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:42,
        name:"Business Card",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:43,
        name:"Supernova",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:44,
        name:"Ride the Bus",
        text:"",
        rarity:1,
        price:6
    },
    {
        id:45,
        name:"Space Joker",
        text:"",
        rarity:2,
        price:5
    },
    {
        id:46,
        name:"Egg",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:47,
        name:"Burglar",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:48,
        name:"Blackboard",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:49,
        name:"Runner",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:50,
        name:"Ice Cream",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:51,
        name:"DNA",
        text:"",
        rarity:3,
        price:8
    },
    {
        id:52,
        name:"Splash",
        text:"",
        rarity:1,
        price:3
    },
    {
        id:53,
        name:"Blue Joker",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:54,
        name:"Sixth Sense",
        text:"",
        rarity:3,
        price:6
    },
    {
        id:55,
        name:"Constellation",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:56,
        name:"Hiker",
        text:"",
        rarity:2,
        price:5
    },
    {
        id:57,
        name:"Faceless Joker",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:58,
        name:"Green Joker",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:59,
        name:"Superposition",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:60,
        name:"To Do List",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:61,
        name:"Cavendish",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:62,
        name:"Card Sharp",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:63,
        name:"Red Card",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:64,
        name:"Madness",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:65,
        name:"Square Joker",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:66,
        name:"Séance",
        text:"",
        rarity:3,
        price:7
    },
    {
        id:67,
        name:"Riff-Raff",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:68,
        name:"Vampire",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:69,
        name:"Shortcut",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:70,
        name:"Hologram",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:71,
        name:"Vagabond",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:72,
        name:"Baron",
        text:"",
        rarity:3,
        price:8
    },
    {
        id:73,
        name:"Cloud 9",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:74,
        name:"Rocket",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:75,
        name:"Obelisk",
        text:"",
        rarity:3,
        price:8
    },
    {
        id:76,
        name:"Midas Mask",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:77,
        name:"Luchador",
        text:"",
        rarity:2,
        price:5
    },
    {
        id:78,
        name:"Photograph",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:79,
        name:"Gift Card",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:80,
        name:"Turtle Bean",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:81,
        name:"Erosion",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:82,
        name:"Reserved Parking",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:83,
        name:"Mail-In Rebate",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:84,
        name:"To the Moon",
        text:"",
        rarity:2,
        price:5
    },
    {
        id:85,
        name:"Hallucination",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:86,
        name:"Fortune Teller",
        text:"",
        rarity:1,
        price:6
    },
    {
        id:87,
        name:"Juggler",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:88,
        name:"Drunkard",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:89,
        name:"Stone Joker",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:90,
        name:"Golden Joker",
        text:"",
        rarity:1,
        price:6
    },
    {
        id:91,
        name:"Lucky Cat",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:92,
        name:"Baseball Card",
        text:"",
        rarity:3,
        price:8
    },
    {
        id:93,
        name:"Bull",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:94,
        name:"Diet Cola",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:95,
        name:"Trading Card",
        text:"",
        rarity:2,
        price:5
    },
    {
        id:96,
        name:"Flash Card",
        text:"",
        rarity:2,
        price:5
    },
    {
        id:97,
        name:"Popcorn",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:98,
        name:"Spare Trousers",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:99,
        name:"Ancient Joker",
        text:"",
        rarity:3,
        price:8
    },
    {
        id:100,
        name:"Ramen",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:101,
        name:"Walkie Talkie",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:102,
        name:"Seltzer",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:103,
        name:"Castle",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:104,
        name:"Smiley Face",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:105,
        name:"Campfire",
        text:"",
        rarity:3,
        price:9
    },
    {
        id:106,
        name:"Golden Ticket",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:107,
        name:"Mr. Bones",
        text:"",
        rarity:2,
        price:5
    },
    {
        id:108,
        name:"Acrobat",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:109,
        name:"Sock and Buskin",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:110,
        name:"Swashbuckler",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:111,
        name:"Troubadour",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:112,
        name:"Certificate",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:113,
        name:"Smeared Joker",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:114,
        name:"Throwback",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:115,
        name:"Hanging Chad",
        text:"",
        rarity:1,
        price:4
    },
    {
        id:116,
        name:"Rough Gem",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:117,
        name:"Bloodstone",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:118,
        name:"Arrowhead",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:119,
        name:"Onyx Agate",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:120,
        name:"Glass Joker",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:121,
        name:"Showman",
        text:"",
        rarity:2,
        price:5
    },
    {
        id:122,
        name:"Flower Pot",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:123,
        name:"Blueprint",
        text:"",
        rarity:3,
        price:10
    },
    {
        id:124,
        name:"Wee Joker",
        text:"",
        rarity:3,
        price:8
    },
    {
        id:125,
        name:"Merry Andy",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:126,
        name:"Oops! All 6s",
        text:"",
        rarity:2,
        price:4
    },
    {
        id:127,
        name:"The Idol",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:128,
        name:"Seeing Double",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:129,
        name:"Matador",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:130,
        name:"Hit the Road",
        text:"",
        rarity:3,
        price:8
    },
    {
        id:131,
        name:"The Duo",
        text:"",
        rarity:3,
        price:8
    },
    {
        id:132,
        name:"The Trio",
        text:"",
        rarity:3,
        price:8
    },
    {
        id:133,
        name:"The Family",
        text:"",
        rarity:3,
        price:8
    },
    {
        id:134,
        name:"The Order",
        text:"",
        rarity:3,
        price:8
    },
    {
        id:135,
        name:"The Tribe",
        text:"",
        rarity:3,
        price:8
    },
    {
        id:136,
        name:"Stuntman",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:137,
        name:"Invisible Joker",
        text:"",
        rarity:3,
        price:10
    },
    {
        id:138,
        name:"Brainstorm",
        text:"",
        rarity:3,
        price:10
    },
    {
        id:139,
        name:"Satellite",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:140,
        name:"Shoot the Moon",
        text:"",
        rarity:1,
        price:5
    },
    {
        id:141,
        name:"Driver's License",
        text:"",
        rarity:3,
        price:7
    },
    {
        id:142,
        name:"Cartomancer",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:143,
        name:"Astronomer",
        text:"",
        rarity:2,
        price:8
    },
    {
        id:144,
        name:"Burnt Joker",
        text:"",
        rarity:2,
        price:6
    },
    {
        id:145,
        name:"Bootstraps",
        text:"",
        rarity:2,
        price:7
    },
    {
        id:146,
        name:"Canio",
        text:"",
        rarity:4,
        price:0
    },
    {
        id:147,
        name:"Triboulet",
        text:"",
        rarity:4,
        price:0
    },
    {
        id:148,
        name:"Yorick",
        text:"",
        rarity:4,
        price:0
    },
    {
        id:149,
        name:"Chicot",
        text:"",
        rarity:4,
        price:0
    },
    {
        id:150,
        name:"Perkeo",
        text:"",
        rarity:4,
        price:0
    }
];






const rarity = ["Common", "Uncommon", "Rare", "Legendary"];


